// quick-starts/vue-solana-quick-start/src/components/sendVersionedTransaction.vue
<script setup lang="ts">
import { ref } from "vue";
import { useWeb3Auth } from "@web3auth/modal/vue";
import { useSolanaWallet, useSignAndSendTransaction } from "@web3auth/modal/vue/solana";

import { buildSolTransferTransaction } from "../solana/transfer";

// Build a SOL transfer with Solana Kit, then sign AND broadcast it with the
// embedded wallet. `signature` is the base58 transaction signature.
const { web3Auth } = useWeb3Auth();
const { accounts } = useSolanaWallet();
const { data: signature, error, loading: isPending, signAndSendTransaction } = useSignAndSendTransaction();
const formError = ref<string | null>(null);

async function submit(event: Event) {
  event.preventDefault();
  formError.value = null;

  const rpcTarget = web3Auth.value?.currentChain?.rpcTarget;
  if (!rpcTarget || !accounts.value?.length) return;

  const form = new FormData(event.target as HTMLFormElement);
  const to = form.get("address")?.toString().trim() ?? "";
  const amountSol = Number(form.get("value"));
  if (!to || !Number.isFinite(amountSol) || amountSol <= 0) {
    formError.value = "Enter a valid recipient address and a positive amount.";
    return;
  }

  try {
    const transaction = await buildSolTransferTransaction(rpcTarget, accounts.value[0], to, amountSol);
    await signAndSendTransaction(transaction);
  } catch (err) {
    formError.value = err instanceof Error ? err.message : "Failed to send transaction.";
  }
}
</script>

<template>
  <div>
    <h2>Send Transaction</h2>
    <form @submit.prevent="submit">
      <input name="address" placeholder="Recipient address" required />
      <input name="value" placeholder="Amount (SOL)" type="number" step="0.01" min="0" required />
      <button type="submit" :disabled="isPending">
        {{ isPending ? "Sending..." : "Send" }}
      </button>
    </form>
    <div v-if="signature" class="hash">Transaction signature: {{ signature }}</div>
    <div v-if="formError ?? error?.message" class="error">Error: {{ formError ?? error?.message }}</div>
  </div>
</template>

// quick-starts/react-solana-quick-start/src/components/sendVersionedTransaction.tsx
import { FormEvent, useState } from "react";
import { useWeb3Auth } from "@web3auth/modal/react";
import { useSolanaWallet, useSignAndSendTransaction } from "@web3auth/modal/react/solana";

import { buildSolTransferTransaction } from "../solana/transfer";

// Build a SOL transfer with Solana Kit, then sign AND broadcast it with the
// embedded wallet. `signature` is the base58 transaction signature.
export function SendVersionedTransaction() {
  const { web3Auth } = useWeb3Auth();
  const { accounts } = useSolanaWallet();
  const { data: signature, error, loading: isPending, signAndSendTransaction } = useSignAndSendTransaction();
  const [formError, setFormError] = useState<string | null>(null);

  async function submit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault();
    setFormError(null);

    const rpcTarget = web3Auth?.currentChain?.rpcTarget;
    if (!rpcTarget || !accounts?.length) return;

    const form = new FormData(e.currentTarget);
    const to = form.get("address")?.toString().trim() ?? "";
    const amountSol = Number(form.get("value"));
    if (!to || !Number.isFinite(amountSol) || amountSol <= 0) {
      setFormError("Enter a valid recipient address and a positive amount.");
      return;
    }

    try {
      const transaction = await buildSolTransferTransaction(rpcTarget, accounts[0], to, amountSol);
      await signAndSendTransaction(transaction);
    } catch (err) {
      setFormError(err instanceof Error ? err.message : "Failed to send transaction.");
    }
  }

  return (
    <div>
      <h2>Send Transaction</h2>
      <form onSubmit={submit}>
        <input name="address" placeholder="Recipient address" required />
        <input name="value" placeholder="Amount (SOL)" type="number" step="0.01" min="0" required />
        <button disabled={isPending} type="submit">
          {isPending ? "Sending..." : "Send"}
        </button>
      </form>
      {signature && <div className="hash">Transaction signature: {signature}</div>}
      {(formError ?? error?.message) && <div className="error">Error: {formError ?? error?.message}</div>}
    </div>
  );
}
