// quick-starts/vue-solana-quick-start/src/components/switchNetwork.vue
<script setup lang="ts">
import { computed } from "vue";
import { useWeb3Auth, useSwitchChain } from "@web3auth/modal/vue";

const { web3Auth, chainId } = useWeb3Auth();
const { switchChain, loading, error } = useSwitchChain();

const chains = computed(() => web3Auth.value?.coreOptions?.chains ?? []);
const currentChain = computed(() => chains.value.find((c) => c.chainId === chainId.value));
</script>

<template>
  <div>
    <h2>Switch Chain</h2>
    <h3>Connected to {{ currentChain?.displayName }}</h3>
    <button
      v-for="chain in chains"
      :key="chain.chainId"
      :disabled="loading || chainId === chain.chainId"
      type="button"
      class="card"
      @click="switchChain({ chainId: chain.chainId })"
    >
      {{ chain.displayName }}
    </button>
    <div v-if="loading" class="loading">Switching chain...</div>
    <div v-if="error" class="error">Error: {{ error.message }}</div>
  </div>
</template>

// quick-starts/react-solana-quick-start/src/components/switchNetwork.tsx
import { useSwitchChain, useWeb3Auth } from "@web3auth/modal/react";

export function SwitchChain() {
  const { web3Auth } = useWeb3Auth();
  const { switchChain, loading, error } = useSwitchChain();

  return (
    <div>
      <h2>Switch Chain</h2>
      <h3>Connected to {web3Auth?.currentChain?.displayName}</h3>
      {web3Auth?.coreOptions.chains?.map((chain) => (
        <button
          key={chain.chainId}
          type="button"
          className="card"
          disabled={loading || web3Auth?.currentChain?.chainId === chain.chainId}
          onClick={() => switchChain(chain.chainId)}
        >
          {chain.displayName}
        </button>
      ))}
      {loading && <div className="loading">Switching chain...</div>}
      {error && <div className="error">Error: {error.message}</div>}
    </div>
  );
}
