// other/sns-example/src/components/getBalance.tsx
import { useSolanaWallet } from "@web3auth/modal/react/solana";
import { address } from "@solana/kit";
import { useEffect, useState } from "react";

export function Balance() {
  const { accounts, rpc } = useSolanaWallet();
  const [balance, setBalance] = useState<number | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fetchBalance = async () => {
    if (!rpc || !accounts || accounts.length === 0) return;
    try {
      setIsLoading(true);
      setError(null);
      const { value } = await rpc.getBalance(address(accounts[0])).send();
      setBalance(Number(value) / 1e9);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Unknown error");
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchBalance();
  }, [rpc, accounts]);

  return (
    <div>
      <h2>Balance</h2>
      <div>
        {balance !== null && `${balance} SOL`}
      </div>
      {isLoading && <span className="loading">Loading...</span>}
      {error && <span className="error">Error: {error}</span>}
      <button onClick={fetchBalance} type="submit" className="card">
        Fetch Balance
      </button>
    </div>
  );
}

// quick-starts/vue-solana-quick-start/src/components/getBalance.vue
<script setup lang="ts">
import { address } from "@solana/kit";
import { ref } from "vue";
import { useSolanaWallet } from "@web3auth/modal/vue/solana";

const { accounts, rpc } = useSolanaWallet();

const balance = ref<string | null>(null);
const loading = ref(false);
const error = ref<string | null>(null);

async function fetchBalance() {
  if (!rpc.value || !accounts.value?.length) return;

  loading.value = true;
  error.value = null;
  try {
    const { value } = await rpc.value.getBalance(address(accounts.value[0])).send();
    balance.value = `${Number(value) / 1e9} SOL`;
  } catch (e) {
    error.value = e instanceof Error ? e.message : "Failed to fetch balance.";
  } finally {
    loading.value = false;
  }
}
</script>

<template>
  <div>
    <h2>Balance</h2>
    <div v-if="balance">{{ balance }}</div>
    <button type="button" class="card" :disabled="loading" @click="fetchBalance">
      {{ loading ? "Fetching..." : "Fetch Balance" }}
    </button>
    <div v-if="error" class="error">Error: {{ error }}</div>
  </div>
</template>
