// other/sns-example/src/components/sendVersionedTransaction.tsx
import { FormEvent } from "react";
import { useSolanaWallet, useSignAndSendTransaction } from "@web3auth/modal/react/solana";
import {
  address,
  appendTransactionMessageInstruction,
  compileTransaction,
  createNoopSigner,
  createTransactionMessage,
  lamports,
  pipe,
  setTransactionMessageFeePayerSigner,
  setTransactionMessageLifetimeUsingBlockhash,
} from "@solana/kit";
import { getTransferSolInstruction } from "@solana-program/system";

export function SendVersionedTransaction() {
  const { data: hash, error, loading: isPending, signAndSendTransaction } = useSignAndSendTransaction();
  const { accounts, rpc } = useSolanaWallet();

  async function submit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault();
    const formData = new FormData(e.target as HTMLFormElement);
    const to = formData.get("address") as string;
    const value = formData.get("value") as string;

    if (!rpc || !accounts) return;

    const { value: latestBlockhash } = await rpc.getLatestBlockhash().send();

    const feePayer = createNoopSigner(address(accounts[0]));
    const message = pipe(
      createTransactionMessage({ version: 0 }),
      (m) => setTransactionMessageFeePayerSigner(feePayer, m),
      (m) => setTransactionMessageLifetimeUsingBlockhash(latestBlockhash, m),
      (m) =>
        appendTransactionMessageInstruction(
          getTransferSolInstruction({
            source: feePayer,
            destination: address(to),
            amount: lamports(BigInt(Math.floor(Number(value) * 1e9))),
          }),
          m,
        ),
    );

    signAndSendTransaction(compileTransaction(message));
  }

  return (
    <div>
      <h2>Send Versioned Transaction</h2>
      <form onSubmit={submit}>
        <input name="address" placeholder="Address" required />
        <input
          name="value"
          placeholder="Amount (SOL)"
          type="number"
          step="0.01"
          required
        />
        <button disabled={isPending} type="submit">
          {isPending ? "Confirming..." : "Send"}
        </button>
      </form>
      {hash && <div>Transaction Hash: {hash}</div>}
      {error && <div>Error: {error.message}</div>}
    </div>
  );
}

// quick-starts/vue-solana-quick-start/src/components/sendVersionedTransaction.vue
<script setup lang="ts">
import { ref } from "vue";
import { useSolanaWallet, useSignAndSendTransaction } from "@web3auth/modal/vue/solana";

import { buildSolTransferTransaction } from "../solana/transfer";

// Build a SOL transfer with Solana Kit, then sign AND broadcast it with the
// embedded wallet. `signature` is the base58 transaction signature.
const { accounts, rpc } = useSolanaWallet();
const { data: signature, error, loading: isPending, signAndSendTransaction } = useSignAndSendTransaction();
const formError = ref<string | null>(null);

async function submit(event: Event) {
  event.preventDefault();
  formError.value = null;

  if (!rpc.value || !accounts.value?.length) return;

  const form = new FormData(event.target as HTMLFormElement);
  const to = form.get("address")?.toString().trim() ?? "";
  const amountSol = Number(form.get("value"));
  if (!to || !Number.isFinite(amountSol) || amountSol <= 0) {
    formError.value = "Enter a valid recipient address and a positive amount.";
    return;
  }

  try {
    const transaction = await buildSolTransferTransaction(rpc.value, accounts.value[0], to, amountSol);
    await signAndSendTransaction(transaction);
  } catch (err) {
    formError.value = err instanceof Error ? err.message : "Failed to send transaction.";
  }
}
</script>

<template>
  <div>
    <h2>Send Transaction</h2>
    <form @submit.prevent="submit">
      <input name="address" placeholder="Recipient address" required />
      <input name="value" placeholder="Amount (SOL)" type="number" step="0.01" min="0" required />
      <button type="submit" :disabled="isPending">
        {{ isPending ? "Sending..." : "Send" }}
      </button>
    </form>
    <div v-if="signature" class="hash">Transaction signature: {{ signature }}</div>
    <div v-if="formError ?? error?.message" class="error">Error: {{ formError ?? error?.message }}</div>
  </div>
</template>
