// other/smart-account-example/src/components/Balance.tsx
import { useConnection, useBalance } from "wagmi";
import { formatUnits } from "viem";

export function Balance() {
  const { address } = useConnection()

  const { data: default_ } = useBalance({ address })

  return (
    <div>
      <h2>Balance</h2>

      <div>Balance: {default_?.value !== undefined ? `${formatUnits(default_.value, default_.decimals)} ${default_.symbol}` : 'Loading...'}</div>
    </div>
  )
}

// quick-starts/vue-quick-start/src/components/Balance.vue
<script setup lang="ts">
import { useConnection, useBalance } from "@wagmi/vue";
import { formatUnits } from "viem";

const { address } = useConnection();
const { data, isLoading, error } = useBalance({ address });
</script>

<template>
  <div>
    <h2>Balance</h2>
    <div v-if="data?.value !== undefined">
      {{ formatUnits(data.value, data.decimals) }} {{ data.symbol }}
    </div>
    <div v-if="isLoading" class="loading">Loading...</div>
    <div v-if="error" class="error">Error: {{ error.message }}</div>
  </div>
</template>
